apiVersion: apps/v1
kind: Deployment
metadata:
  name: prueba
  namespace: aplicacion
spec:
  selector:
    matchLabels:
      clave: valor
  replicas: 0
  template:
    metadata:
      labels:
        clave: valor
    spec:
      containers:
        - name: ejemplo
          image: ggmartinez/prueba
          ports:
            - containerPort: 80
            - containerPort: 443
          env:
            - name: VARIABLE
              value: valor
